version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_mm
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mm
    volumes:
      - ./db/mm.sql:/docker-entrypoint-initdb.d/1.mm.sql
  web:
    build: .
    container_name: web_mm
    links:
     - mysql
    ports:
     - "8081:80"
    volumes:
     - ./:/var/www/html
